voyage_homepage:
    path:     /
    defaults: { _controller: VoyageBundle:Default:index }
voyage_read:
    path:     /readVoyage
    defaults: { _controller: VoyageBundle:Voyage:readVoyage }
voyage_create:
    path:     /createVoyage
    defaults: { _controller: VoyageBundle:Voyage:createVoyage }
voyage_delete:
  path:     /deleteVoyage/{id}
  defaults: { _controller: VoyageBundle:Voyage:deleteVoyage }
voyage_update:
  path:     /updateVoyage/{id}
  defaults: { _controller: VoyageBundle:Voyage:updateVoyage }
voyage_read_resev:
  path:     /readVReserver
  defaults: { _controller: VoyageBundle:reservationVoyage:readVoyageAReserver }
voyage_resever:
  path:     /ReserverVoyage/{id}
  defaults: { _controller: VoyageBundle:reservationVoyage:ReserverVoyage }



